task: detection

num_classes: 80
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: MTSDDetectionCL

    img_folder: mtsd/mtsd_train/
    ann_file: mtsd/annotations/instances_train_c1.json

    transforms:
      type: Compose
      ops: ~

val_dataloader:
  type: DataLoader
  dataset:
    type: MTSDDetectionCL

    img_folder: mtsd/mtsd_val/
    ann_file: mtsd/annotations/instances_val_c1.json

    transforms:
      type: Compose
      ops: ~
