# WandB
wandb_mode: "disabled"
wandb_name: "4040_t0_prompt"

# CL Strategy
pseudo_label: False
distill_attn: False
teacher_path: "../detrw/7010/7010_t0_10e_ap5474.pth"
# CL General
# start_task: 0
# total_tasks: 2

# CL Rehearsal
# rehearsal: False

# CL Eval
# fpp: False
