# WandB
wandb_mode: "online"
wandb_name: "4040_t0_lora-linear+conv+embed"

# LoRA
lora_train: True
lora_val: True
lora_id: "outputs/weights/lora_4040_t0_1"

# CL Strategy
pseudo_label: False
distill_attn: False
teacher_path: "../detrw/7010/7010_t0_10e_ap5474.pth"
# CL General
# start_task: 0
# total_tasks: 2

# CL Rehearsal
# rehearsal: False

# CL Eval
# fpp: False
